### ISSUE TITLE
Fix Proguard configuration

### ISSUE THREAD

**Issue by klinker24** [klinker41/article-android#22]
I have not been able to get the library to work with Proguard yet. Even ignoring it seems to cause issues. 

I don't know a whole lot about how proguard works, to be honest, but could it have something to do with that libraries dependencies not being excluded correctly? I think it is very telling that requests aren't going through at all. Perhaps something with `Retrofit`? I don't think that the issue is with the actual API uri getting lost or anything, but like I said, I don't think I know enough about how it works!

This was originally tracked [here](https://github.com/klinker-apps/messenger-issues/issues/175), but I wanted to move it here, so that anyone looking to use this library will know of the issue.

**Comment by klinker41** [comment]
Sorry for taking so long on this, fixed with https://github.com/klinker41/article-android/commit/223ccf117c9159ff2517fa20d38430e0b3e8c831.

The trick was to add `-keep class xyz.klinker.android.article.data.Article { *; }`. I also added all of the configs for libraries that we depend on. The root of the problem was retrofit uses reflection (or maybe generates code, not sure which) to interact with it's services. This meant that it was looking for that Article class, except it wasn't there cause it was being renamed by proguard.
